### ISSUE TITLE
Set size of vertex icons

### ISSUE THREAD

**Issue by jekuno** [Leaflet/Leaflet.Editable#114]
In desktop browsers we need bigger vertex icons for usability reasons. Currently in `Leaflet.Editable` the size is hardcoded as follows:

```
L.Editable.VertexIcon = L.DivIcon.extend({
        options: {
            iconSize: new L.Point(8, 8)
        }
});
```

It would be nice if the `iconSize` could be passed upon initialization of Leaflet.Editable e.g as an option when calling `enableEdit()`.

**Comment by db255** [comment]
+1
You can hack the size in CSS with something like:

```css
.leaflet-vertex-icon {
    max-width: 10px;
    max-height: 10px;
    margin-left: -5px !important;
    margin-top: -5px !important;
}
.leaflet-middle-icon {
    max-width: 10px;
    max-height: 10px;
    margin-left: -5px !important;
    margin-top: -5px !important;
}
```

But you still have the MiddleMarker visibility set by the hardcoded iconSize:
```javascript
size = L.point(this.options.icon.options.iconSize);
if (leftPoint.distanceTo(rightPoint) < size.x * 3) this.hide();
```
